# In this Notebook we are going to learn fundamentals of tensor using Tensorflow

We are going to cover

* Intro to Tensor
* Getting info from tensors
* Manipulating Tensors
* Tensors and Numpy
* USing @tf.function (way to speed up regular functions)
* Using GPU with Tensorflow
* Excercises to try

## Introduction to Tensors

In [4]:
# Import TensorFlow

import tensorflow as tf

print(tf.__version__)

2.4.1


In [7]:
# Create tensors with tf.constant()

scalar = tf.constant(7)

(scalar)

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [8]:
# check number of dimensions in a tensor

scalar.ndim

0

In [10]:
# Create a vector 

vector = tf.constant([10,10])

vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [11]:
# check the dimensions of vector

vector.ndim

1

In [14]:
# create a matrix

matrix = tf.constant([[1,2],[3,4]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [15]:
# check the dimensions of matrix

matrix.ndim

2

In [21]:
# create another matrix

another_matrix = tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0],[7.0,8.0,9.0]],dtype=tf.float16)

another_matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float16)>

In [22]:
# check dimensions of another matrix

another_matrix.ndim

2

In [26]:
yet_another_matrix = tf.constant([[[1,2,3],[4,5,6]],
                                  [[7,8,9],[10,11,12]],
                                  [[13,14,15],[16,17,18]]
                                  ])

yet_another_matrix

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [27]:
yet_another_matrix.ndim

3

What we did so far

* scalar : a single number
* vector: a number with direction
* Matrix: a 2 dimensinol number array
* Tensor: an n- dimensional array 