# In this Notebook we are going to learn fundamentals of tensor using Tensorflow

We are going to cover

* Intro to Tensor
* Getting info from tensors
* Manipulating Tensors
* Tensors and Numpy
* USing @tf.function (way to speed up regular functions)
* Using GPU with Tensorflow
* Excercises to try

## Introduction to Tensors

In [2]:
# Import TensorFlow

import tensorflow as tf

print(tf.__version__)

2.4.1


In [3]:
# Create tensors with tf.constant()

scalar = tf.constant(7)

(scalar)

2023-07-17 23:40:56.349624: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2023-07-17 23:40:56.352626: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# check number of dimensions in a tensor

scalar.ndim

0

In [5]:
# Create a vector 

vector = tf.constant([10,10])

vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# check the dimensions of vector

vector.ndim

1

In [7]:
# create a matrix

matrix = tf.constant([[1,2],[3,4]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [8]:
# check the dimensions of matrix

matrix.ndim

2

In [9]:
# create another matrix

another_matrix = tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0],[7.0,8.0,9.0]],dtype=tf.float16)

another_matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float16)>

In [10]:
# check dimensions of another matrix

another_matrix.ndim

2

In [11]:
yet_another_matrix = tf.constant([[[1,2,3],[4,5,6]],
                                  [[7,8,9],[10,11,12]],
                                  [[13,14,15],[16,17,18]]
                                  ])

yet_another_matrix

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
yet_another_matrix.ndim

3

What we did so far

* scalar : a single number
* vector: a number with direction
* Matrix: a 2 dimensinol number array
* Tensor: an n- dimensional array 

### Creating tensors with tf.variable

In [18]:
#  create tensors like above
changaleble_tensor = tf.Variable([10,10])
unchangable_tensor = tf.constant([10,10])

changaleble_tensor,unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>)

In [20]:
changaleble_tensor [0] = 7

TypeError: 'ResourceVariable' object does not support item assignment

In [22]:
changaleble_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [23]:
unchangable_tensor[0]=7

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [24]:
unchangable_tensor[0].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

rarely we use tf.constant and tf.variable when creating models. when in doubt create tf.constant and chnage it later according to need

### Creating Random tensors

Random Tensors are tensors of some abitrary size which contain random numbers. When creating neural networks we start with random tensors for weights thats where we use this

In [27]:
# Create a random tensors

random1 = tf.random.Generator.from_seed(42).normal(shape=(3,2)) # Seed used for reproductability
random1 

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [28]:
random2 = tf.random.Generator.from_seed(42).uniform(shape=(3,2)) # Seed used for reproductability
random2 

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

### Shuffle Data in tensors

Used to shuffle data so that there would be no input order bias

In [29]:
# shuffle tensor

not_shuffled = tf.constant([[10,7],[1,2],[3,4]])

In [30]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 1,  2],
       [ 3,  4]], dtype=int32)>

In [36]:
tf.random.shuffle(not_shuffled,seed=3)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 1,  2]], dtype=int32)>

### Other ways to make tensors

In [37]:
import numpy as np

In [39]:
# create tensor all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [41]:
# create tensor of all zeros
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

#### Turn numpy arrays to tensors

We can turn numpy arrays into Tensors. The main diff between numpy arrays and tensors are that tensors can be run on GPU fast

In [49]:
numpy_A = np.arange(25,dtype=np.int32).reshape((5,5))
numpy_A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]], dtype=int32)

In [50]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]], dtype=int32)>

In [52]:
numpy_B = np.arange(24,dtype=np.int32)
B = tf.constant(numpy_B,shape=(2,3,4))
B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]], dtype=int32)>

### Getting more info from tensors
 
- Shape - length of each of the dimensions pf tensor - tensor.shape
- Rank - No of dimensions - tensor.ndim
- Axis or Dimension - A particular dimension of tensor - tensor[0],tensor[1]
- Size - Total number of items in a tensor - tf.size(tensor)

In [53]:
# Create a rank four sensor

Array_c = np.arange(40).reshape((2,2,2,5))
C = tf.constant(Array_c)

C

<tf.Tensor: shape=(2, 2, 2, 5), dtype=int64, numpy=
array([[[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]],


       [[[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]],

        [[30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]]]])>

In [57]:
C[0]

<tf.Tensor: shape=(2, 2, 5), dtype=int64, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])>

In [58]:
C.shape

TensorShape([2, 2, 2, 5])

In [59]:
C.ndim

4

In [60]:
tf.size(C)

<tf.Tensor: shape=(), dtype=int32, numpy=40>

In [ ]:
###